[[redirects]]
 from = "/*"
 to = "/index.html"
 status = 200

[[redirects]]
 from = "/contact"
 to = "/contact.html" 
 status = 200

[[redirects]]
 from = "/register"  
 to = "/register.html"
 status = 200